### ISSUE TITLE
Cannot convert prometheus CRDs to json schema

### ISSUE THREAD

**Issue by dobesv** [yannh/kubeconform#90]
When trying to convert the prometheus CRDs to json schema, I get this error from the python script:

```
$ python3 ~/kubeconform/scripts/openapi2jsonschema.py https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/bundle.yaml
Traceback (most recent call last):
  File "/home/ubuntu/kubeconform/scripts/openapi2jsonschema.py", line 123, in <module>
    for y in yaml.load_all(f, Loader=yaml.SafeLoader):
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 130, in load_all
    yield loader.get_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 45, in get_data
    return self.construct_document(self.get_node())
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:value'
  in "<file>", line 2789, column 29
```

I messed around a bit trying to figure it out, but to no avail.  Has anyone seen this error before?

**Comment by dobesv** [comment]
Hmm actually it seems like PyYAML doesn't like having a string value starting with `=`.  Interesting, I wonder if that's actually a yaml requirement.

**Comment by luisdavim** [comment]
Did you report this upstream?

**Comment by dobesv** [comment]
I didn't report it anywhere else.  I just manually corrected the file to quote those values and moved on.  I don't know whether PyYAML or the prometheus CRD file is the one that needs correcting.
